# ชื่อ Plugin ต้องตรงกับชื่อไฟล์ JAR และ Class หลัก
name: DialoguesEconomy
main: com.nonkungch.dialogueseconomy.DialoguesEconomy
version: ${project.version} # กำหนดเวอร์ชันของคุณ
api-version: 1.13 # หรือเวอร์ชันที่สูงกว่า (แนะนำ 1.16 ขึ้นไป)
author: NonKungCh

# คำสั่ง (Commands)
commands:
  dialogue:
    description: Start, stop, or manage dialogue sequences.
    usage: |
      /dialogue start <player> <file> - เริ่มบทสนทนา
      /dialogue stop <player> - ยุติบทสนทนา
      /dialogue create <file> - สร้างไฟล์ dialogue ใหม่
      /dialogue reload - โหลด config ใหม่
    permission: dialogueseconomy.admin
    aliases: [dia] 

  balance:
    description: Shows your current economy balance using Vault.
    usage: /balance
    permission: dialogueseconomy.balance

# Dependencies ที่จำเป็น
depend:
  - Vault
  
# Dependencies ที่แนะนำ (ถ้ามี Plugin นี้ Plugin จะทำงานได้ดีขึ้น)
softdepend:
  - PlaceholderAPI

# Permissions (ตัวอย่าง)
permissions:
  dialogueseconomy.admin:
    description: Allows full access to dialogue administration commands.
    default: op
  dialogueseconomy.balance:
    description: Allows players to check their balance.
    default: true
