name: DialoguesEconomy
version: 1.0
main: com.yourname.dialogueplugin.DialoguesEconomy
api-version: 1.13 

# ==================================
# ข้อมูลผู้สร้าง
# ==================================
author: NonKungCh # ใส่ชื่อของคุณ หรือชื่อทีม
website: https://github.com/NonCraftStudio/DialoguesEconomy # (ไม่บังคับ)

commands:
  dialogue:
    description: Start or manage a dialogue sequence.
    usage: /dialogue <id>
    aliases: [dia] 
  dialogue_choice:
    description: Internal command for dialogue choices. Do not use directly.
    permission: dialogue.internal 

depend:
  - Vault
  - PlaceholderAPI 
softdepend:
  - Floodgate
