name: DialoguesEconomy
version: 1.0.1
main: com.nonkungch.dialogueseconomy.DialoguesEconomy
api-version: 1.21
author: NonKungCh
description: Dialogue + Economy system for Minecraft

# Dependencies
depend: [Vault, PlaceholderAPI]

# Commands
commands:
  dialogue:
    description: หลักสำหรับจัดการบทสนทนา / Main dialogue command
    usage: /<command> <start|click|stop|reload|create> [args]
    aliases: [dia]
    permission: dialogue.use
    permission-message: "&cคุณไม่มีสิทธิ์ใช้คำสั่งนี้!"

# Permissions
permissions:
  dialogue.use:
    description: ใช้คำสั่ง DialoguesEconomy ได้ / Can use dialogue commands
    default: true
