name: Build DialoguesEconomy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧱 Checkout Repository
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: 🔧 Build with Maven
        run: mvn clean package

      - name: 📦 Upload Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DialoguesEconomy
          path: target/*.jar
